name: My first CI
on:
  push:
  workflow_dispatch:
jobs:
  set_env:
    runs-on: ubuntu-latest

    steps:

    - name: Set up JDK '17'
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: zulu

    - name: Echo Java version
      run: java -version

    - name: Checkout
      uses: actions/checkout@v4.1.3

    - name: Current dir
      run: pwd

    - name: List files
      run: ls -ltr

    - name: Build app
      run: mvn package -DskipTests

    - name: Run Test
      run: mvn test
